for(var i = 0; i < 205; i++) { var scriptId = 'u' + i; window[scriptId] = document.getElementById(scriptId); }

$axure.eventManager.pageLoad(
function (e) {

});
gv_vAlignTable['u115'] = 'center';gv_vAlignTable['u7'] = 'top';gv_vAlignTable['u99'] = 'center';gv_vAlignTable['u4'] = 'top';gv_vAlignTable['u17'] = 'top';gv_vAlignTable['u135'] = 'center';gv_vAlignTable['u151'] = 'center';gv_vAlignTable['u159'] = 'top';gv_vAlignTable['u55'] = 'center';gv_vAlignTable['u101'] = 'center';gv_vAlignTable['u186'] = 'top';gv_vAlignTable['u105'] = 'center';gv_vAlignTable['u27'] = 'top';gv_vAlignTable['u67'] = 'center';gv_vAlignTable['u11'] = 'top';gv_vAlignTable['u6'] = 'top';gv_vAlignTable['u37'] = 'center';gv_vAlignTable['u141'] = 'center';gv_vAlignTable['u21'] = 'top';gv_vAlignTable['u133'] = 'center';gv_vAlignTable['u200'] = 'top';gv_vAlignTable['u89'] = 'center';gv_vAlignTable['u47'] = 'center';gv_vAlignTable['u184'] = 'top';gv_vAlignTable['u185'] = 'top';gv_vAlignTable['u103'] = 'center';gv_vAlignTable['u31'] = 'center';gv_vAlignTable['u179'] = 'top';gv_vAlignTable['u57'] = 'center';gv_vAlignTable['u191'] = 'top';u203.tabIndex = 0;

u203.style.cursor = 'pointer';
$axure.eventManager.click('u203', function(e) {

if (true) {

	self.location.href=$axure.globalVariableProvider.getLinkUrl('经纪公司管理.html');

}
});
gv_vAlignTable['u203'] = 'top';gv_vAlignTable['u125'] = 'center';gv_vAlignTable['u41'] = 'center';gv_vAlignTable['u172'] = 'top';gv_vAlignTable['u149'] = 'center';gv_vAlignTable['u197'] = 'top';gv_vAlignTable['u189'] = 'top';gv_vAlignTable['u176'] = 'top';gv_vAlignTable['u174'] = 'top';gv_vAlignTable['u119'] = 'center';gv_vAlignTable['u85'] = 'center';gv_vAlignTable['u51'] = 'center';gv_vAlignTable['u182'] = 'top';gv_vAlignTable['u77'] = 'center';gv_vAlignTable['u202'] = 'top';gv_vAlignTable['u95'] = 'center';gv_vAlignTable['u61'] = 'center';gv_vAlignTable['u33'] = 'center';gv_vAlignTable['u75'] = 'top';gv_vAlignTable['u157'] = 'top';gv_vAlignTable['u71'] = 'center';gv_vAlignTable['u181'] = 'top';gv_vAlignTable['u198'] = 'top';gv_vAlignTable['u5'] = 'top';gv_vAlignTable['u79'] = 'center';gv_vAlignTable['u127'] = 'center';gv_vAlignTable['u43'] = 'top';gv_vAlignTable['u169'] = 'top';gv_vAlignTable['u187'] = 'top';gv_vAlignTable['u154'] = 'top';gv_vAlignTable['u139'] = 'center';gv_vAlignTable['u87'] = 'center';gv_vAlignTable['u53'] = 'center';gv_vAlignTable['u192'] = 'top';gv_vAlignTable['u121'] = 'center';gv_vAlignTable['u19'] = 'top';gv_vAlignTable['u65'] = 'center';gv_vAlignTable['u109'] = 'center';gv_vAlignTable['u97'] = 'center';gv_vAlignTable['u123'] = 'top';gv_vAlignTable['u81'] = 'center';gv_vAlignTable['u177'] = 'top';gv_vAlignTable['u190'] = 'top';gv_vAlignTable['u73'] = 'center';gv_vAlignTable['u113'] = 'center';gv_vAlignTable['u147'] = 'center';gv_vAlignTable['u163'] = 'top';gv_vAlignTable['u91'] = 'top';gv_vAlignTable['u131'] = 'center';gv_vAlignTable['u188'] = 'top';gv_vAlignTable['u23'] = 'top';gv_vAlignTable['u204'] = 'top';gv_vAlignTable['u117'] = 'center';gv_vAlignTable['u13'] = 'top';gv_vAlignTable['u29'] = 'center';gv_vAlignTable['u111'] = 'center';gv_vAlignTable['u175'] = 'top';gv_vAlignTable['u129'] = 'center';gv_vAlignTable['u183'] = 'top';gv_vAlignTable['u173'] = 'top';gv_vAlignTable['u39'] = 'center';gv_vAlignTable['u171'] = 'top';gv_vAlignTable['u145'] = 'center';gv_vAlignTable['u63'] = 'center';gv_vAlignTable['u83'] = 'center';gv_vAlignTable['u178'] = 'top';gv_vAlignTable['u8'] = 'top';gv_vAlignTable['u196'] = 'top';gv_vAlignTable['u15'] = 'top';gv_vAlignTable['u49'] = 'center';gv_vAlignTable['u1'] = 'center';gv_vAlignTable['u93'] = 'center';gv_vAlignTable['u167'] = 'top';gv_vAlignTable['u201'] = 'top';gv_vAlignTable['u165'] = 'top';gv_vAlignTable['u199'] = 'top';gv_vAlignTable['u25'] = 'top';gv_vAlignTable['u59'] = 'top';gv_vAlignTable['u137'] = 'center';gv_vAlignTable['u161'] = 'top';gv_vAlignTable['u45'] = 'center';gv_vAlignTable['u143'] = 'center';gv_vAlignTable['u107'] = 'top';gv_vAlignTable['u35'] = 'center';gv_vAlignTable['u69'] = 'center';gv_vAlignTable['u180'] = 'top';gv_vAlignTable['u3'] = 'center';